In [127]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, KFold, LeaveOneOut, cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score
knn = KNeighborsClassifier(n_neighbors=3)

In [128]:
# 1 dataset <-- titanic.csv
dataset = pd.read_csv('titanic.csv')
print(dataset.head())

   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S

In [129]:
# 3 train_data <-- ambil dataset kolom fitur (Sex, Age, Pclass, Fare). Lakukan pengisian
# missing value pada fitur Age dengan nilai mean dari masing-masing class

dataset['Age'].fillna(dataset.groupby('Survived')['Age'].transform('mean'), inplace=True)
train_data = dataset.loc[:,['Sex', 'Age', 'Pclass', 'Fare']]
print(f"Data train: \n{train_data.head()}")

Data train:
      Sex   Age  Pclass     Fare
0    male  22.0       3   7.2500
1  female  38.0       1  71.2833
2  female  26.0       3   7.9250
3  female  35.0       1  53.1000
4    male  35.0       3   8.0500

In [130]:
# 4. label <-- ambil dataset kolom kelas (Survived)

label = dataset.loc[:, ['Survived']]
label = np.array(label).ravel()
print(f"label : \n{label}")

label :
[0 1 1 1 0 0 0 0 1 1 1 1 0 0 0 1 0 1 0 1 0 1 1 1 0 1 0 0 1 0 0 1 1 0 0 0 1
 0 0 1 0 0 0 1 1 0 0 1 0 0 0 0 1 1 0 1 1 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 0 0
 1 0 0 0 1 1 0 1 1 0 1 1 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 1 0 0 0 0 1 0 0 1 0 0 0 0 1 1 0 0 0 1 0
 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1
 0 1 1 0 0 1 0 1 1 1 1 0 0 1 0 0 0 0 0 1 0 0 1 1 1 0 1 0 0 0 1 1 0 1 0 1 0
 0 0 1 0 1 0 0 0 1 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 1 1
 1 0 1 0 0 0 0 0 1 1 1 0 1 1 0 1 1 0 0 0 1 0 0 0 1 0 0 1 0 1 1 1 1 0 0 0 0
 0 0 1 1 1 1 0 1 0 1 1 1 0 1 1 1 0 0 0 1 1 0 1 1 0 0 1 1 0 1 0 1 1 1 1 0 0
 0 1 0 0 1 1 0 1 1 0 0 0 1 1 1 1 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 1 1 1 1
 1 0 0 0 0 1 1 0 0 0 1 1 0 1 0 0 0 1 0 1 1 1 0 1 1 0 0 0 0 1 1 0 0 0 0 0 0
 1 0 0 0 0 1 0 1 0 1 1 0 0 0 0 0 0 0 0 1 1 0 1 1 1 1 0 0 1 0 1 0 0 1 0 0 1
 1 1 1 1 1 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 1 0
 0 0 1 1 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 1 1 0 1 1 0 1 1 0 0 1 0
 1 0 1 0 0 1 0 0 1 0 0 0 1 0 0 1 0 1 0 1 0 1 1 0 0 1 0 0 1 1 0 1 1 0 0 1 1
 0 1 0 1 1 0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 0 1 1 0 1 1 1 0 0 0 1 0 1 0 0 0 1
 0 0 0 0 1 0 0 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 0 1 0 0 1 0 0 1 1 0 0 0 0 1 0
 0 1 0 1 0 0 1 0 0 0 0 0 1 0 1 1 1 0 1 0 1 0 1 0 1 0 0 0 0 0 0 1 0 0 0 1 0
 0 0 0 1 1 0 0 1 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 1 0 0 1 1 0
 0 0 0 1 1 1 1 1 0 1 0 0 0 1 1 0 0 1 0 0 0 1 0 1 1 0 0 1 0 0 0 0 0 0 1 0 0
 1 0 1 0 1 0 0 1 0 0 1 1 0 0 1 1 0 0 0 1 0 0 1 1 0 1 0 0 0 0 0 0 0 0 1 0 0
 1 0 1 1 1 0 0 0 0 1 0 1 0 0 0 0 0 0 0 1 1 0 0 0 1 1 1 1 0 0 0 0 1 0 0 0 0
 0 0 0 0 0 0 1 1 0 1 0 0 0 1 1 1 1 1 0 0 0 1 0 0 1 1 0 0 1 0 0 0 0 0 0 1 0
 0 0 1 0 1 1 1 1 0 0 0 1 0 0 1 1 0 0 1 0 1 0 0 1 1 0 0 0 1 1 0 0 0 0 0 0 1
 0 1 0]

In [131]:
# 5. train_data <-- lakukan normalisasi pada train_data dengan Min-Max 0-1 (catat nilai
# min dan max setiap atribut)

scaler = MinMaxScaler()
train_data[['Age', 'Pclass', 'Fare']] = scaler.fit_transform(train_data[['Age', 'Pclass', 'Fare']])
min_values = scaler.data_min_
max_values = scaler.data_max_

print(f'hasil normalisasi: \n{train_data.head()}\n')
print(f'nilai min setelah normalisasi: \n{min_values}')
print(f'nilai max setelah normalisasi: \n{max_values}')

hasil normalisasi:
      Sex       Age  Pclass      Fare
0    male  0.271174     1.0  0.014151
1  female  0.472229     0.0  0.139136
2  female  0.321438     1.0  0.015469
3  female  0.434531     0.0  0.103644
4    male  0.434531     1.0  0.015713

nilai min setelah normalisasi:
[0.42 1.   0.  ]
nilai max setelah normalisasi:
[ 80.       3.     512.3292]

In [132]:
# 6. test_data <-- lakukan normalisasi pada train_data dengan min-max pada Langkah 5

def minmax(x, min, max):
    return (x - min) / (max - min)


test_data = minmax(train_data[['Age', 'Pclass', 'Fare']], min_values, max_values)

print(f'hasil normalisasi: \n{test_data.head()}\n')

hasil normalisasi:
        Age  Pclass      Fare
0 -0.001870     0.0  0.000028
1  0.000656    -0.5  0.000272
2 -0.001239     0.0  0.000030
3  0.000183    -0.5  0.000202
4  0.000183     0.0  0.000031

In [133]:
# 2a Hold-out Method (70%-30%)

train_data = pd.get_dummies(train_data, columns=['Sex'], drop_first=True)
X_train, X_test, y_train, y_test = train_test_split(train_data, label, test_size=0.3, random_state=42)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
accuracy_holdout = accuracy_score(y_test, y_pred)

In [134]:
# 2b K-Fold (k=10)

kf = KFold(n_splits=10, shuffle=True, random_state=42)
scores_kfold = cross_val_score(knn, train_data, label, cv=kf)
accuracy_kfold = scores_kfold.mean()

In [135]:
# 2c LOO

loo = LeaveOneOut()
scores_loo = cross_val_score(knn, train_data, label, cv=loo)
accuracy_loo = scores_loo.mean()

In [136]:
# 7. Lakukan klasifikasi k-NN (k=3) untuk masing-masing pendekatan validasi dan
# hitunglah error ratio-nya

# Menghitung error ratio untuk setiap pendekatan
error_ratio_holdout = 1 - accuracy_holdout
error_ratio_kfold = 1 - accuracy_kfold
error_ratio_loo = 1 - accuracy_loo

# Menampilkan hasil error ratio
print("Error Ratio Hold-out (70%-30%):", error_ratio_holdout)
print("Error Ratio K-Fold (k=10):", error_ratio_kfold)
print("Error Ratio Leave-One-Out (LOO):", error_ratio_loo)

Error Ratio Hold-out (70%-30%): 0.15298507462686572
Error Ratio K-Fold (k=10): 0.16051186017478147
Error Ratio Leave-One-Out (LOO): 0.1582491582491582